//
//  Configuration.h
//  UberAPI
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 05/09/2016
//
#ifndef UberAPI_Configuration_h
#define UberAPI_Configuration_h

/** The base Uri for API calls */
extern NSString* Configuration_BaseUri;

/** The OAuth 2.0 access token to be set before API calls */
/** extern reference to the config variable OAuthAccessToken */
extern NSString* Configuration_OAuthAccessToken;

#endif
