//
//  GetPriceEstimatesInput.m
//  UberAPI
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 05/09/2016
//
#import "GetPriceEstimatesInput.h"

@implementation GetPriceEstimatesInput

/**
* Latitude component of start location.
*/
@synthesize startLatitude;

/**
* Longitude component of start location.
*/
@synthesize startLongitude;

/**
* Latitude component of end location.
*/
@synthesize endLatitude;

/**
* Longitude component of end location.
*/
@synthesize endLongitude;

@end