//
//  GetPromotionsInput.h
//  UberAPI
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 05/09/2016
//
#ifndef APIMATIC_GETPROMOTIONSINPUT
#define APIMATIC_GETPROMOTIONSINPUT

#import <Foundation/Foundation.h>
#import "JSONModel.h"
#import "APIHelper.h"



//protocol defined for deserialization of JSON
@protocol GetPromotionsInput
@end

@interface GetPromotionsInput : NSObject

/**
* Latitude component of start location.
*/
@property double startLatitude;

/**
* Longitude component of start location
*/
@property double startLongitude;

/**
* Latitude component of end location.
*/
@property double endLatitude;

/**
* Longitude component of end location.
*/
@property double endLongitude;

@end
#endif